{{- range $name, $hpa := .Values.hpas }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $hpa.name | default $name }}
  {{- with $hpa.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $hpa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ $hpa.scaleTargetRef.apiVersion | default "apps/v1" }}
    kind: {{ $hpa.scaleTargetRef.kind | default "Deployment" }}
    name: {{ $hpa.scaleTargetRef.name }}
  minReplicas: {{ $hpa.minReplicas | default 1 }}
  maxReplicas: {{ $hpa.maxReplicas | default 5 }}
  metrics:
    {{- toYaml $hpa.metrics | nindent 4 }}
---
{{- end }}
