{{- range $name, $pvc := .Values.pvcs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvc.name | default $name }}
  {{- with $pvc.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $pvc.spec | nindent 2 }}
---
{{- end }}
