{{- range $name, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | default $name | quote }}
  {{- with $secret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- if or $secret.data $secret.stringData }}
{{- with $secret.data }}
data:
  {{- range $key, $val := . }}
  {{ $key | quote }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- with $secret.stringData }}
stringData:
  {{- range $key, $val := . }}
  {{ $key | quote }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
