{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name | default $name }}
  {{- with $service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  selector:
    {{- toYaml $service.selector | nindent 4 }}
  ports:
    {{- toYaml $service.ports | nindent 4 }}
---
{{- end }}
